%%{init: {'theme':'dark', 'themeVariables': {'fontSize':'16px'}}}%%
flowchart LR
    NEMO(["NVIDIA NeMo"])

    NEMO --> NER["NER"]
    NEMO --> QA["Question Answering"]
    NEMO --> TC["Text Classification"]
    NEMO --> PUNC["Punctuation"]
    NEMO --> MT["Machine Translation"]
    NEMO --> TTS["Text-to-Speech"]

    classDef hijau fill:#76B900,stroke:#5a8f00,stroke-width:2px,color:#000000;
    class NEMO hijau;